#!/usr/bin/env bash
# Fetch the review conversation that already exists on an MR, keyed by file, and
# mark which of it the user wrote themselves.
#
# Usage:
#   existing-threads.sh --project <numeric-id> --mr <iid>
#
# Published discussions and unpublished drafts are separate endpoints; merging
# them is what keeps a group header from re-raising a point already made.
# `humanPaths` is also the only record of review progress that survives a posted
# batch, since the local scratch file is deleted at that point.
#
# A note counts as the user's own when it carries the `<!-- human-review -->`
# marker, or when they authored it and it is not agent-generated — which covers
# notes typed straight into the GitLab UI. `review-mr` posts under the same
# account, so author identity alone would count its findings as the user's; they
# are excluded by their "Generated by AI" footer.
#
# Prints:
#   {
#     "self": {"id":N,"username":"…"},
#     "files": {
#       "path/to/file.ts": {
#         "threads": [{"id","author","line","resolved","body","mine","agent","human"}],
#         "drafts":  [{"id","line","body","mine","agent","human"}]
#       }, …
#     },
#     "humanPaths": ["…"],
#     "lastHuman": {"kind":"draft|note","path","line","body","at"} | null,
#     "counts": {"threads":N,"drafts":N,"human":N}
#   }
#
# Non-positional notes (general MR comments) are collected under the "" key, and
# never appear in `humanPaths` — they say nothing about which files were walked.
#
# `lastHuman` prefers the newest draft (drafts are unpublished, so they are the
# most recent work by construction) and falls back to the newest published note.
# It is orientation for the user, not the resume calculation: `review-state.sh`
# derives the group to continue at from `humanPaths` against the plan.

set -euo pipefail

die() { echo "existing-threads.sh: $*" >&2; exit 1; }

project=""; mr=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --project) project="$2"; shift 2 ;;
    --mr)      mr="$2"; shift 2 ;;
    *) die "unknown arg: $1" ;;
  esac
done

[[ -n "$project" ]] || die "--project required"
[[ -n "$mr" ]]      || die "--mr required"
command -v glab >/dev/null 2>&1 || die "glab not found on PATH"
command -v jq   >/dev/null 2>&1 || die "jq not found on PATH"

base="projects/$project/merge_requests/$mr"

# Every call is best-effort: a token without read access to one endpoint should
# not take down the whole group header.
discussions=$(glab api --paginate "$base/discussions" 2>/dev/null || echo '[]')
drafts=$(glab api --paginate "$base/draft_notes" 2>/dev/null || echo '[]')
self=$(glab api "user" 2>/dev/null || echo '{}')

# `glab api --paginate` concatenates JSON arrays across pages; normalise to one.
discussions=$(jq -s 'if length == 0 then [] else add end' <<<"$discussions" 2>/dev/null || echo '[]')
drafts=$(jq -s 'if length == 0 then [] else add end' <<<"$drafts" 2>/dev/null || echo '[]')

jq -n --argjson d "$discussions" --argjson n "$drafts" --argjson me "$self" '
  def marker: "<!-- human-review -->";
  def strip_marker: (. // "") | sub("\n*" + marker + "\\s*$"; "");
  def clip: if (. | length) > 160 then .[0:160] + "…" else . end;
  # review-mr signs its notes; without this every agent finding on the MR would look
  # like a comment the user wrote.
  def agent_written: test("Generated by AI");

  ($me.id // null) as $myId
  | ($me.username // null) as $myName
  | ([ $d[]
     | . as $disc
     | .notes[]?
     | select(.system | not)
     | ((.author.id // null) as $aid | (.author.username // null) as $aname
        | ($myId != null and $aid == $myId) or ($myName != null and $aname == $myName)) as $mine
     | ((.body // "") | test(marker)) as $marked
     | ((.body // "") | agent_written) as $agent
     | {
         path:     (.position.new_path // .position.old_path // ""),
         id:       ($disc.id // ""),
         author:   (.author.username // "?"),
         line:     (.position.new_line // .position.old_line // null),
         resolved: (.resolved // false),
         at:       (.created_at // null),
         body:     ((.body // "") | strip_marker | clip),
         mine:     $mine,
         agent:    $agent,
         human:    ($marked or ($mine and ($agent | not)))
       } ]) as $threads
  | ([ $n[]
     | (($myId != null and (.author_id // null) == $myId) or ($myId == null)) as $mine
     | ((.note // "") | test(marker)) as $marked
     | ((.note // "") | agent_written) as $agent
     | {
         path: (.position.new_path // ""),
         id:   .id,
         line: (.position.new_line // null),
         body: ((.note // "") | strip_marker | clip),
         mine: $mine,
         agent: $agent,
         human: ($marked or ($mine and ($agent | not)))
       } ]) as $draftNotes
  | ( ($threads | map(.path)) + ($draftNotes | map(.path)) | unique ) as $paths
  | {
      self: {id: $myId, username: $myName},
      files: (reduce $paths[] as $p ({};
        . + { ($p): {
            threads: [ $threads[]    | select(.path == $p) | del(.path, .at) ],
            drafts:  [ $draftNotes[] | select(.path == $p) ]
          } })),
      humanPaths: ( [ ($threads + $draftNotes)[]
                      | select(.human and .path != "") | .path ] | unique ),
      lastHuman: (
        ([ $draftNotes[] | select(.human and .path != "") ] | sort_by(.id) | last) as $ld
        | ([ $threads[] | select(.human and .path != "") ] | sort_by(.at // "") | last) as $lt
        | if   $ld then {kind:"draft", path:$ld.path, line:$ld.line, body:$ld.body, at:null}
          elif $lt then {kind:"note",  path:$lt.path, line:$lt.line, body:$lt.body, at:$lt.at}
          else null end
      ),
      counts: {
        threads: ($threads | length),
        drafts:  ($draftNotes | length),
        human:   ([ ($threads + $draftNotes)[] | select(.human) ] | length)
      }
    }
'
